### ISSUE TITLE
gh-pages

### ISSUE THREAD

**Issue by gyorvaripeter** [Teaching-projects/SZE-MOSZE-2020-Kumisztan--Closed#6]
Please @hegyhati give me permission for **gh-pages** branch.

**Comment by hegyhati** [comment]
Ez megkesve erkezett kisse. Jogosultsagod van a gh-pages branchre a kezdetek ota.

**Comment by gyorvaripeter** [comment]
Elnézést rosszul fogalmaztam. 
A github pages beállítását szeretném kérvényezni
Az előbbiekben megnevezett branchen.

**Comment by hegyhati** [comment]
done.
